options:
    pdi_url:
        type: string
        default: 'http://downloads.sourceforge.net/project/pentaho/Data%20Integration/6.0/pdi-ce-6.0.1.0-386.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fpentaho%2Ffiles%2FData%2520Integration%2F6.0%2F&ts=1454506997&use_mirror=netix#sha256=98a1877977cfba5c2ea40baf23921d418068d3ff19d5f949b85b0b036a45cb85'
        description: 'PDI Download URL. By default this points to the latest download from sourceforge.net'
    carte_port:
        type: string
        default: '9999'
        description: 'The default Carte port for remote job execution and monitoring.'
    java_opts:
        type: string
        default: ''
        description: 'Override the default JAVA_OPTS to set memory limits etc.'
    carte_password:
          type: string
          default: 'cluster'
          description: 'The password used to connect to Carte.'