#!/usr/bin/env bash
set -ex


path=`action-get path`
javaopts=`action-get java-opts`
loglevel=`action-get log-level`
logfile=`action-get log-file`
params=`action-get parameters`
cron=`action-get cron-entry`

fullloglevel=''
fulllogfile=''
fullparams=''
fulljavaopts=''


if [ -n "${loglevel}" ]
 then
    fullloglevel="-level ${loglevel}"
fi

if [ -n "${logfile}" ]
 then
    fulllogfile="-logfile ${logfile}"
fi

if [ -n "${params}" ]
 then
    fullparams="-param ${params}"
fi

if [ -n "${javaopts}" ]
 then
    fulljavaopts="JAVAOPTS=${javaopts}"
fi

exe="${fulljavaopts} /opt/data-integration/kitchen.sh -file=${path} ${fullloglevel} ${fulllogfile} ${fullparams}"

  juju-log "Command to be executed is: ${exe}"

if [ -z "${cron}" ]
 then
  juju-log "Executing ETL: ${path}"
  eval "${exe}"
  action-set outcome="ETL execution finished"
 else
  juju-log "Scheduling ETL: ${path} at ${cron}"
  echo "# /etc/cron.d/anacron: crontab entries for the anacron package
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
${cron}   etl    ${exe}
" > /etc/cron.d/job_$(basename ${path})_${cron}
   action-set outcome="ETL scheduled"
fi