#!/usr/bin/env bash
set -ex


PATH=action-get path
JAVAOPTS=action-get java_opts
LOGLEVEL=action-get log_level
LOGFILE=action-get log_file
PARAMS=action-get parameters
CRON=action-get cron-entry

fullloglevel=''
fulllogfile=''
fullparams=''
fulljavaopts=''


if [ -z "${LOGLEVEL}" ]
 then
    FULLLOGLEVEL="-level ${LOGLEVEL}"
fi

if [ -z "${LOGFILE}" ]
 then
    FULLLOGFILE="-logfile ${LOGFILE}"
fi

if [ -z "${PARAMS}" ]
 then
    FULLPARAMS="-param ${PARAMS}"
fi

if [ -z "${JAVAOPTS}" ]
 then
    FULLJAVAOPTS="-param ${JAVAOPTS}"
fi

EXE=${FULLJAVAOPTS} /opt/data-integration/pan.sh -file=${PATH} ${FULLLOGLEVEL} ${FULLLOGFILE} ${FULLPARAMS}

  juju-log "Command to be executed is: ${exe}"

if [ -z "${CRON}" ]
 then
  juju-log "Executing ETL: ${PATH}"
  eval EXE
  action-set outcome="ETL execution finished"
 else
  juju-log "Scheduling ETL: ${PATH} at ${CRON}"
  echo "# /etc/cron.d/anacron: crontab entries for the anacron package
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
${CRON}   etl    ${EXE}
" > /etc/cron.d/$(basename ${PATH})_$(cat /proc/sys/kernel/random/uuid)
   action-set outcome="ETL scheduled"
fi