#!/usr/bin/env bash
set -ex


TRANSPATH=`action-get path`
JAVAOPTS=`action-get java-opts`
LOGLEVEL=`action-get log-level`
LOGFILE=`action-get log-file`
PARAMS=`action-get parameters`
CRON=`action-get cron-entry`

fullloglevel=''
fulllogfile=''
fullparams=''
fulljavaopts=''


if [ -n "${LOGLEVEL}" ]; then
    FULLLOGLEVEL="-level ${LOGLEVEL}"
fi

if [ -n "${LOGFILE}" ]; then
    FULLLOGFILE="-logfile ${LOGFILE}"
fi

if [ -n "${PARAMS}" ]; then
    FULLPARAMS="-param ${PARAMS}"
fi

if [ -n "${JAVAOPTS}" ]; then
    FULLJAVAOPTS="JAVA_OPTS=${JAVAOPTS}"
fi

ETLEXE="${FULLJAVAOPTS} /opt/data-integration/pan.sh -file=${TRANSPATH} ${FULLLOGLEVEL} ${FULLLOGFILE} ${FULLPARAMS}"

juju-log "Command to be executed is: ${ETLEXE}"

if [ -z "${CRON}" ];
 then
  juju-log "Executing ETL: ${ETLEXE}"
  eval "${ETLEXE}"
  action-set outcome="ETL execution finished"
 else
  juju-log "Scheduling ETL: ${TRANSPATH} at ${CRON}"
  echo "# /etc/cron.d/anacron: crontab entries for the anacron package
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
${CRON}   etl    ${ETLEXE}
" > /etc/cron.d/transformation_$(basename ${TRANSPATH})_${CRON}
   action-set outcome="ETL scheduled"
fi